name: Starter CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Setup pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8.x # Or a specific version like 8.10.0

      - name: Install dependencies 
        run: |
          pnpm install --frozen-lockfile 

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Lint
        run: pnpm run lint
